package net.ronm19.lunarismod.entity.client;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class VoidEyeAnimations {

    public static final AnimationDefinition ANIM_VOID_EYE_IDLE = AnimationDefinition.Builder.withLength(2f).looping()
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 7.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -7.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 7.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(0f, -7.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("halo",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition ANIM_VOID_EYE_WALKING = AnimationDefinition.Builder.withLength(6.75f).looping()
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("halo",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-0.2f, 0f, -0.1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.25f, KeyframeAnimations.posVec(0.6f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0.95f, 0f, 0.15f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(1.4f, 0f, 0.3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.posVec(1.9f, 0f, 0.8f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.25f, KeyframeAnimations.posVec(2.2f, 0f, 1.3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.posVec(2.2f, 0f, 1.2f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.75f, KeyframeAnimations.posVec(2.5f, 0f, 1.9f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.posVec(2.8f, 0f, 2.4f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.25f, KeyframeAnimations.posVec(2.8f, 0f, 3.3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.5f, KeyframeAnimations.posVec(2.8f, 0f, 4f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.75f, KeyframeAnimations.posVec(2.6f, 0f, 4.7f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3f, KeyframeAnimations.posVec(2f, 0f, 5.7f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.25f, KeyframeAnimations.posVec(1.3f, 0f, 6.4f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.5f, KeyframeAnimations.posVec(0.2f, 0f, 6.7f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.75f, KeyframeAnimations.posVec(-1f, 0f, 6.8f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4f, KeyframeAnimations.posVec(-2f, 0f, 6.4f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.25f, KeyframeAnimations.posVec(-2.6f, 0f, 5.8f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.5f, KeyframeAnimations.posVec(-3.4f, 0f, 4.8f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.75f, KeyframeAnimations.posVec(-3.7f, 0f, 4.3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5f, KeyframeAnimations.posVec(-3.9f, 0f, 3.4f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.25f, KeyframeAnimations.posVec(-3.8f, 0f, 2.6f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.5f, KeyframeAnimations.posVec(-3.5f, 0f, 1.6f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.75f, KeyframeAnimations.posVec(-3.22f, -0.03f, 0.44f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6f, KeyframeAnimations.posVec(-2.7f, -0.1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.25f, KeyframeAnimations.posVec(-1.4f, 0f, 0.1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.5f, KeyframeAnimations.posVec(-1.1f, 0.1f, -0.3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.541677f, KeyframeAnimations.posVec(-3.83f, 0.08f, 1.91f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.583433f, KeyframeAnimations.posVec(-3.1f, 0.07f, 5.17f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.625f, KeyframeAnimations.posVec(-0.65f, 0.05f, 6.7f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.676667f, KeyframeAnimations.posVec(2f, 0.03f, 4.93f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.708343f, KeyframeAnimations.posVec(2.3f, 0.02f, 2.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.75f, KeyframeAnimations.posVec(-0.2f, 0f, -0.1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("halo",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -7.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, -15f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -32.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, -45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, -52.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(0f, -62.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, -72.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(0f, -87.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, -97.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, -112.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, -127.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(0f, -142.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, -160f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.75f, KeyframeAnimations.degreeVec(0f, -181f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(0f, -196f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.25f, KeyframeAnimations.degreeVec(0f, -210f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(0f, -230f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.75f, KeyframeAnimations.degreeVec(0f, -242.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5f, KeyframeAnimations.degreeVec(0f, -254.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.25f, KeyframeAnimations.degreeVec(0f, -266.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.5f, KeyframeAnimations.degreeVec(0f, -286.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.75f, KeyframeAnimations.degreeVec(0f, -299f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, -311.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.25f, KeyframeAnimations.degreeVec(0f, -326.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.5f, KeyframeAnimations.degreeVec(0f, -340.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
}
